// Add steps as necessary for accessing the software, post-configuration, and testing. Don’t include full usage instructions for your software, but add links to your product documentation for that information.
//Should any sections not be applicable, remove them

== Post-deployment steps
// If post-deployment steps are required, add them here. If not, remove the heading

In the CloudFormation console,, locate the values in the *Outputs* tab. Then log in to the application by targeting the hostname you provided for the application server (or the AWS-generated DNS name for the port 80 front-end load Application Load Balancer, if you chose an insecure installation). 

The initial admininstrator user name is localadmin@datarobot.com. The password is located in AWS Secrets Manager in the account you used to install the Quick Start.

After logging in, open the menu in the upper-right corner of the window to find the option for inserting the license key you received from DataRobot.

== Best practices for using {partner-product-short-name} on AWS
// Provide post-deployment best practices for using the technology on AWS, including considerations such as migrating data, backups, ensuring high performance, high availability, etc. Link to software documentation for detailed information.

Keep training data relatively small to avoid incurring incremental costs. For more information, including a tutorial and an instroduction to DataRobot, see the https://api-docs.datarobot.com/docs/quickstart-guide[DataRobot Quickstart Guide]. 

== Security
// Provide post-deployment best practices for using the technology on AWS, including considerations such as migrating data, backups, ensuring high performance, high availability, etc. Link to software documentation for detailed information.

Do not use or share the localadmin@datarobot.com user name. Only use it to create separate accounts for each user and then assign the appropriate permissions by role.

If you initially chose an HTTP installation, edit the front-end Application Load Balancers by changing the listeners to port 443 and adding the certificates you control to secure the installation.
The installation uses your default Amazon Elastic Block Store (Amazon EBS) encryption key for the installation Region. Use a different key if your security policies require it.
The base installation creates a crontab entry to dump data into a backup directory on the S3 bucket at midnight. Change this S3 bucket to be your backup directory for data and retention processes and policies.

== Other useful information
//Provide any other information of interest to users, especially focusing on areas where AWS or cloud usage differs from on-premises usage.

The installation is designed to auto scale to 10 workers. If you need more than 10 for your training models, contact sales@datarobot.com to request support and additional capacity.
